### ISSUE TITLE
Function array_swap_item references array_swap

### ISSUE THREAD

**Issue by nwwdles** [vladdeSV/gm_extensions#2]
This makes YYC fail. I believe it should have array_swap_item there.
https://github.com/vladdeSV/gm_extensions/blob/01ed3a4bdac8c79afacd4c566eea4e95cf9081d5/scripts/extension_array.gml#L571

**Comment by vladdeSV** [comment]
True indeed, will fix in a minute!

**Comment by vladdeSV** [comment]
Should be fixed as of v1.1.1
